#!/bin/bash

set -e

#Argument parsing
COMMAND="$1"
shift || true

MODEL="$1"
shift || true

VERSION=""
FILE=""
USER="tedge"

while [ $# -gt 0 ]; do
	case $1 in
		--module-version)
		    VERSION="$2"
		    shift 2
		    ;;
		--file)
		    FILE="$2"
		    shift 2
		    ;;
		*)
		    echo "Unknown option: $1" >&2
		    echo "Usage: $0 <name> --module-version <version> --file <path>"
		    exit 1
		    ;;
  esac
done

BASE_MODEL_DIR="/etc/tedge/plugins/vai-plugin/model"

case "$COMMAND" in
    list)
        for dir in "${BASE_MODEL_DIR}"/*/; do
          if [ -f "${dir}version" ]; then
            # Read the content of version.txt
            v=$(<"${dir}version")
            # Output: foldername<TAB>version
            printf '%s\t%s\n' "$(basename "${dir}")" "$v"
          fi
        done
        exit 0
        ;;
    install)
        TARGET_DIR="${BASE_MODEL_DIR}/${MODEL}"
        mkdir -p "$TARGET_DIR"
        # Unzip the file
        echo "Unzipping file..."
        unzip -o "$FILE" -d "$TARGET_DIR"
        echo ${VERSION} > "$TARGET_DIR"/version
        chown -R "$USER":"$USER" "$TARGET_DIR"

        echo "Model update completed successfully."
        exit 0
        ;;
    remove)
        TARGET_DIR="${BASE_MODEL_DIR}/${MODEL}"
        rm -rf "$TARGET_DIR"
        exit 0
        ;;
    prepare)
        ;;
    finalize)
        ;;
    update-list)
        exit 1
        ;;
esac
exit 0
