name: Build and Release Debian Package

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install just
      - name: Install just
        run: |
          curl -sL https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      # Build both architectures using the justfile
      - name: Build Debian Packages
        run: just

      # Upload the .deb packages
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-packages
          path: /work/*.deb
