name: Check on PRs

on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Set up Docker Buildx for advanced features like caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install just
        uses: taiki-e/install-action@just 

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        
      - name: Run Unit tests
        run: just test-units

      # Build both architectures using the justfile
      - name: Build Debian Packages
        run: just
